development:
  adapter: postgresql
  encoding: unicode
  database: blog-app_development
  pool: 5
  host: localhost
  username: newton
  password: 12345

test:
  adapter: postgresql
  encoding: unicode
  database: blog-app_test
  pool: 5
  username: newton
  password: 12345